### ISSUE TITLE
Cowrie: raise NotImplementedError(self.onError)

### ISSUE THREAD

**Issue by kevthehermit** [hpfeeds/hpfeeds#59]
Trying to get Cowrie Docker container running with HPFeeds on Python 3
https://github.com/cowrie/cowrie/issues/1307#issuecomment-592791768

The broker sees auth connections but when it comes to Cowrie publishing messages its getting an error that seems to be in hpfeeds rather than cowrie. 

```
2020-02-29T00:47:25+0000 [HoneyPotSSHTransport,1,172.17.0.1] Connection lost after 58 seconds
2020-02-29T00:47:25+0000 [_Protocol,client] Unhandled Error
        Traceback (most recent call last):
          File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
            why = selectable.doRead()
          File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/internet/tcp.py", line 243, in doRead
            return self._dataReceived(data)
          File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
            return self._wrappedProtocol.dataReceived(data)
          File "/cowrie/cowrie-env/lib/python3.7/site-packages/hpfeeds/twisted/protocol.py", line 98, in dataReceived
            self.messageReceived(opcode, data)
          File "/cowrie/cowrie-env/lib/python3.7/site-packages/hpfeeds/twisted/protocol.py", line 78, in messageReceived
            return self.onError(readerror(data))
          File "/cowrie/cowrie-env/lib/python3.7/site-packages/hpfeeds/twisted/protocol.py", line 44, in onError
            raise NotImplementedError(self.onError)
        builtins.NotImplementedError: <bound method BaseProtocol.onError of <hpfeeds.twisted.service._Protocol object at 0x7f25c130c240>>

2020-02-29T00:47:25+0000 [twisted.application.internet.ClientService#info] Scheduling retry 1 to connect <HostnameEndpoint 172.17.0.1:20000> in 2.123090546217142 seconds.
2020-02-29T00:47:25+0000 [hpfeeds.twisted.factory.ClientFactory#info] Stopping factory <hpfeeds.twisted.factory.ClientFactory object at 0x7f25c3772d68>
2020-02-29T00:47:27+0000 [hpfeeds.twisted.factory.ClientFactory#info] Starting factory <hpfeeds.twisted.factory.ClientFactory object at 0x7f25c3772d68>
```

**Comment by kevthehermit** [comment]
OK, found it. It was a missing channel on the Publisher list.
