### ISSUE TITLE
Dirty shutdown behaviour of `hpfeeds.asyncio.ClientSession` used in async context manager

### ISSUE THREAD

**Issue by jgru** [hpfeeds/hpfeeds#65]
Dear `hpfeeds`-maintainers,

I'm trying to achieve a clean shutdown with `hpfeeds.asyncio.ClientSession` on SIGINT. If I just instantiate a ClientSession and use an async for, I can get clean shutdown behaviour with the following code. However if I use a ClientSession in an async with context, I get the the following exception, which I can catch anywhere:
```
Exception in callback _SelectorSocketTransport._call_connection_lost(None)
handle: <Handle _SelectorSocketTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 958, in _call_connection_lost
    super()._call_connection_lost(exc)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 716, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "/media/.../project/venv/lib/python3.8/site-packages/hpfeeds/asyncio/client.py", line 45, in connection_lost
    self.client.when_closed.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state
```
 This is a MWE, that produces the code. Can you help on this? Is it my fault or is there actually a bug in `hpfeeds.asyncio.ClientSession`?
```python
import asyncio
import signal
from hpfeeds.asyncio import ClientSession


# See: https://gist.github.com/nvgoldin/30cea3c04ee0796ebd0489aa62bcf00a
async def shutdown(signal, loop):
    """Cleanup tasks tied to the service's shutdown."""
    print(f"Received exit signal {signal.name}...")

    tasks = [t for t in asyncio.all_tasks() if t is not
             asyncio.current_task()]
    [task.cancel() for task in tasks]

    print(f"Cancelling {len(tasks)} tasks")
    await asyncio.gather(*tasks, return_exceptions=True)

    print(f"Flushing metrics")
    loop.stop()


def register_signals(loop):
    signals = (signal.SIGHUP, signal.SIGTERM, signal.SIGINT)
    for s in signals:
        loop.add_signal_handler(s, lambda s=s: asyncio.create_task(shutdown(s, loop)))


async def pull_with_clean_shutdown():
        client = ClientSession('localhost', 10000, 'reader', 'secret')
        feed = "chan1"
        client.subscribe(feed)
        try:

            async for ident, channel, payload in client:
                pass

        except asyncio.exceptions.CancelledError as e:
            print("Cancellation")


async def pull_with_dirty_shutdown():
    try:
        async with ClientSession('localhost', 10000, 'reader', 'secret') as client:
            feed = "chan1"
            client.subscribe(feed)
            try:
                async for ident, channel, payload in client:
                    if not any(x in channel for x in (';', '"', '{', '}')):
                        pass

            except asyncio.exceptions.CancelledError as e:
                await client.close()
                print("Cancellation")
                client.close()()

    except asyncio.exceptions.CancelledError as e:
        print("Cancellation outer")

loop = asyncio.get_event_loop()
register_signals(loop)
loop.run_until_complete(pull_with_clean_shutdown())
```

Thank you already in advance for a short reply. 

Best regards, 
gru

**Comment by Jc2k** [comment]
Does it happen if you get rid of the client.close()? Async with I think calls close for you, and the error looks like something is closing the connection twice.

**Comment by jgru** [comment]
> Does it happen if you get rid of the client.close()? Async with I think calls close for you, and the error looks like something is closing the connection twice.

Yes, it happens without client.close(), also. My environment is Python 3.8.0 and hpfeeds 3.0.0. 
I had a look in the sources, but could not see the problem...Can somebody help?
